# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-30 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title_slug',
        ),
    ]
