# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_usertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
