# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-10 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20181108_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.CharField(default='Author', max_length=128),
        ),
    ]
