# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-10 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='ABC', max_length=128),
        ),
    ]
