# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-11 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20181110_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Jase Chen', max_length=128),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
