# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-11 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20181111_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('content', mdeditor.fields.MDTextField()),
                ('title_slug', models.SlugField(blank=True)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'pages',
            },
        ),
        migrations.DeleteModel(
            name='Archive',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
