# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-21 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20181118_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='title_slug',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_slug',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
