# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 06:52
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20181120_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=('title', 'content'), unique=True),
        ),
    ]
