# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 16:43
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileHostingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('slug', models.CharField(blank=True, max_length=64, unique=True)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('file_upload', models.FileField(upload_to=api.models.user_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='ImageHostingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('slug', models.CharField(blank=True, max_length=64, unique=True)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('image_upload', models.ImageField(upload_to=api.models.user_image_path)),
            ],
        ),
    ]
