# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-22 17:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190322_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehostingmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
